### PR TITLE
Fix button focus

### PR DESCRIPTION
**Pull request by janette**
DO NOT PULL - FOR QA ONLY!

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://fix-button-focus.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://fix-button-focus.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://fix-button-focus.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://fix-button-focus.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://fix-button-focus.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://fix-button-focus.dkan.qa.nuamsdev.com

**Comment by janette** [comment]
Might need to re-create a QA site, these seem to disappear after a while. 
1. View the :focus state of buttons, they should not be #eee, they should match the color selected in colorizer for active link
2. Go to a dataset page and edit the Additional Info field, add a few items, and save. The table should match the look of the table above it.

**Comment by acouch** [comment]
QA site created: http://fix-button-focus.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
this is working properly

**Comment by acouch** [comment]
QA site created: http://fix-button-focus.dkan.qa.nuamsdev.com

**Pull request closed without merging**
