### PR TITLE
NuCivic/internal#877: visualization embed

### PR DESCRIPTION
**Pull request by dharizza**
This responds to the issue https://github.com/NuCivic/internal/issues/877

Acceptance test:
- [x] Module visualization_entity_embed should be enable by default.
- [x] Test passes (for this we need this PR https://github.com/NuCivic/visualization_entity/pull/34 merged because the tests created here depends on that.)

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://877-enable-visualization-embed.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
Tests pass but module should be enabled by dkan.info if possible, not the install hook.

**Comment by dharizza** [comment]
Done, now the module is enabled by dkan.info instead of the install hook.

**Comment by nucivicmachine** [comment]
QA site created: http://877-enable-visualization-embed.dkan.qa.nuamsdev.com

**Pull request merged**
