### PR TITLE
#1946: Added logged in status to cache hashes for API

### LINKED ISSUE #1946: Issue with Limit Consistency in DataStore API
Looks like there is a bug with ‘limit’ in the API in conjunction with multiple groupbys and/or sum and/or being logged in.  There are different results returned with slightly different combinations, either honoring the limit or not (and returning 100 instead).
     
For example this query:
https://data.louisvilleky.gov/api/action/datastore/search.json?resource_id=6695537a-caab-4731-af84-538ce9146319&group_by=DEPT,BIWEEKLY_PAY_PERIOD_END_DATE&sum=TOTAL_HOURS&limit=1000

Gives either 1000 results if you are **logged into the site**, or 100 if you are not.

But this one returns 200 even if you are not logged in: 
https://data.louisvilleky.gov/api/action/datastore/search.json?resource_id=6695537a-caab-4731-af84-538ce9146319&group_by=DEPT,BIWEEKLY_PAY_PERIOD_END_DATE&sum=TOTAL_HOURS&limit=200

The only change is 1000 vs 200 in the **limit**.

But if you put 150 on the limit, it only returns 100: https://data.louisvilleky.gov/api/action/datastore/search.json?resource_id=6695537a-caab-4731-af84-538ce9146319&group_by=DEPT,BIWEEKLY_PAY_PERIOD_END_DATE&sum=TOTAL_HOURS&limit=150

The only limits that seem to work with that query are 1-100, 200, and 500 for some reason.  Everything else returns 100.

Additionally, if you remove the '**sum**' field, limits seem to work correctly all the time.

Or if you remove the 'DEPT' from the '**group_by**', limits work fine.

Using DKAN 7.x-1.13.3 and Drupal core 7.54

### PR DESCRIPTION
**Pull request by kducharm**
Connects #1946 

## Description
Currently, cache hash doesn't change whether user is logged in or not, so viewing an API URL and then refreshing after logging in doesn't update the limits that are placed on anonymous users. A flag was added to the cache hash to recache the API call once logged in.

## QA Steps
- [x] Import a resource with more than 500 items into the datastore.
- [x] As an anonymous user, visit a dataset API url like /api/action/datastore/search.json?resource_id=XXXXX&limit=500 - you should see max of 100 rows.
- [x] As an logged in user with unlimited query permission (ie admin), visit the same URL - you should see all 500 rows.

## Reminders
- [ ] There is test for the issue.
- [x] CHANGELOG updated.
- [x] Coding standards checked.
- [ ] Review docs.getdkan.com (or in /docs) to see if it still covers the scope of the PR and update if needed.

### CODE REVIEW

**Comment by dkinzer** [comment]
@kristian dkan#1917 is behaving weirdly when I pass it a bogus resource, do you want me to throw back the issue or just treat it as a new one?

https://ba15eb9d-e36c-48e4-821f-df693ed795d7--pr-1971.probo.build/api/action/datastore/search.json?resource_id=XXXXX&limit=500

```
<br />
<b>Fatal error</b>:  Call to a member function arguments() on a non-object in <b>/src/dkan/modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.module</b> on line <b>1115</b><br />
```

**Comment by dkinzer** [comment]
Actually, i'm getting the same error even if I go to the bare URL: https://ba15eb9d-e36c-48e4-821f-df693ed795d7--pr-1971.probo.build/api/action/datastore/search.json

**Comment by kristian** [comment]
@dkinzer, guess you picked the wrong @kristian. Never contributed to this project before. Sorry.

**Comment by dkinzer** [comment]
@kristian ..oops, I did (thanks for the heads up!).

**Comment by dkinzer** [comment]
This is working as expected now.

**Pull request merged**
