### PR TITLE
Moved views featured groups to dkan dataset groups #653

### PR DESCRIPTION
**Pull request by jacintocapote**

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://internal_563_move_featured_groups_into_dkan_dataset_groups.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_563_move_featured_groups_into_dkan_dataset_groups.dkan.qa.nuamsdev.com

**Comment by jacintocapote** [comment]
TEST: Go to admin/structure/views and check that exists featured groups views and the administration view work with dragrableviews.

**Comment by nucivicmachine** [comment]
QA site created: http://internal_563_move_featured_groups_into_dkan_dataset_groups.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_563_move_featured_groups_into_dkan_dataset_groups.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_563_move_featured_groups_into_dkan_dataset_groups.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_563_move_featured_groups_into_dkan_dataset_groups.dkan.qa.nuamsdev.com

**Pull request merged**
