### PR TITLE
Dev dkanextension hooks

### PR DESCRIPTION
**Pull request by frankcarey**
This brings in all the new updates from the dkan extension:
- EntityStore and PageStore are now services instead of contexts (uses Symphony Dependency Injection Containers)
- WorkflowContext.php which contains steps for workflow.
- Can set "created date" now for node entities.
- Dates now work (can use relative dates like "+1 year" or "1 month ago" in your Entity creation steps.
- If a user is logged in before an entity is created, they are assumed to be the author (reduce need to create users in steps."
- More consistent naming of DataStoryContext.php
- Better code comments across the extension
- Status Code fallback when mink driver doesn't support them.
- Lots more tests, especially for pages: See https://github.com/NuCivic/dkanextension/blob/34c48a4ad0f579826889c08cfac895a509ffffbe/src/Drupal/DKANExtension/Context/PageContext.php

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://dev-dkanextension-hooks.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://dev-dkanextension-hooks.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://dev-dkanextension-hooks.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://dev-dkanextension-hooks.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://dev-dkanextension-hooks.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://dev-dkanextension-hooks.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://dev-dkanextension-hooks.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://dev-dkanextension-hooks.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://dev-dkanextension-hooks.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://dev-dkanextension-hooks.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://dev-dkanextension-hooks.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://dev-dkanextension-hooks.dkan.qa.nuamsdev.com

**Comment by frankcarey** [comment]
I double checked, everything in this PR has already been merged into 7.x-1.x

**Pull request closed without merging**
