### PR TITLE
Code review for DKAN Fixtures

### PR DESCRIPTION
**Pull request by dafeder**
Issue: CIVIC-4651

## Description

Implements fixes for all issues found with Drupal code sniffer

## QA Tests

- [x] Tests pass
- [x] Default content still appears as expected on build

### CODE REVIEW

**Comment by dafeder** [comment]
@msolv can you review and merge this?

**Comment by msolv** [comment]
@dafeder Looks good but can you remove '/dkan/dkan_fixtures/dkan_fixtures.sublime-workspace'?

**Comment by dafeder** [comment]
Oops!

**Comment by dafeder** [comment]
@msolv fixed and added .sublime-workspace to .gitignore

**Pull request merged**
