### PR TITLE
Release: Internal 580 user command center

### PR DESCRIPTION
**Pull request by dafeder**
New PR to merge the command center into the release branch first.

### CODE REVIEW

**Comment by dafeder** [comment]
ref NuCivic/internal#580

**Comment by nucivicmachine** [comment]
QA site created: http://internal_580_user_command_center.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_580_user_command_center.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_580_user_command_center.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_580_user_command_center.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_580_user_command_center.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_580_user_command_center.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_580_user_command_center.dkan.qa.nuamsdev.com

**Comment by jacintocapote** [comment]
Ready to test:
"Log in to QA site, and see if command center appears as expected on the user profile page"
"Disable visualization module and check you can't see on the links on the user links dashboard"

**Comment by nucivicmachine** [comment]
QA site created: http://internal_580_user_command_center.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_580_user_command_center.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_580_user_command_center.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_580_user_command_center.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_580_user_command_center.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_580_user_command_center.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_580_user_command_center.dkan.qa.nuamsdev.com

**Pull request merged**
