### PR TITLE
Upgrades travis

### PR DESCRIPTION
**Pull request by acouch**
Upgrades travis. See: http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

### CODE REVIEW

**Comment by acouch** [comment]
```
If you require sudo, for instance to install Ubuntu packages, a workaround is to use precompiled binaries, uploading them to S3 and downloading them as part of your build,then installing them into a non-root directory.```

**Comment by nucivicmachine** [comment]
QA site created: http://upgrade_travis.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://upgrade_travis.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://upgrade_travis.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://upgrade_travis.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://upgrade_travis.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://upgrade_travis.dkan.qa.nuamsdev.com

**Pull request merged**
