### PR TITLE
CIVIC 674 add dkan featured topics to product

### PR DESCRIPTION
**Pull request by dkinzer**
Ref: https://jira.govdelivery.com/browse/CIVIC-674

## Acceptance
- [ ] Open front page, you should see the featured topics block with 12 predefined topics.

### CODE REVIEW

**Comment by SalahMessaoud** [comment]
@dkinzer Looking good but there is some images we don't need eg HHS logo and hero image also some missing CSS we need to get from HHS I noticed that the topics facet is missing as well

**Comment by dkinzer** [comment]
@salahmessaoud facet is not part of acceptance criteria

**Comment by nucivicmachine** [comment]
QA site created: http://c-674-add-dkan-featured-topics-to-product.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://c-674-add-dkan-featured-topics-to-product.dkan.qa.nuamsdev.com

**Pull request merged**
