### PR TITLE
QA Only - Features module update

### PR DESCRIPTION
**Pull request by drkloc**

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://qa_features_modules_update.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://qa_features_modules_update.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://qa_features_modules_update.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://qa_features_modules_update.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
for some reason features 2.5 is not playing nice with either feeds, feeds_field_fetcher or feeds_flatstore_processor.

I'm getting an empty **importerID** while creating the DkanDatastore instance:

screen shot 2015-06-17 at 6 38 01 pm

**Comment by acouch** [comment]
QA site created: http://qa_features_modules_update.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
NuCivic/dkan#467

Now this is passing. Merging update in dkan_dataset.

**Pull request closed without merging**
