### PR TITLE
QA recline & vis_entity branches

### PR DESCRIPTION
**Pull request by janette**
Issue: civic- 2710

## PRs in this build
https://github.com/NuCivic/visualization_entity/pull/45
https://github.com/NuCivic/recline/pull/41 - merged

### CODE REVIEW

**Comment by janette** [comment]
@acouch 

CircleCI fails

[Error] Error while running remake.
PATH=/home/ubuntu/.config/composer/vendor/bin:$PATH bash dkan-init.sh dkan --deps --build=$DATABASE_URL returned exit code 1

Action failed: PATH=/home/ubuntu/.config/composer/vendor/bin:$PATH bash dkan-init.sh dkan --deps --build=$DATABASE_URL

**Comment by janette** [comment]
now it is failing tests on the resource pages

And I am on "Resource 04" page   
And I am on "Resource 05" page

**Comment by dkinzer** [comment]
I'm merging latest dkan to see if that helps.

**Comment by dkinzer** [comment]
timeout, rebuilding

**Comment by dkinzer** [comment]
OK, this finally passed.

**Comment by asghaier** [comment]
@dkinzer this build seems to skip the markdown editor tests. That's why it passed.
I'm not sure if this is the correct behavior that we want.
I pushed a fix for the markdown editor tests and it should fix the failing tests, but I wonder why the previous build skipped the markdown tests.

**Comment by dkinzer** [comment]
@asghaier actually markdown tests were not skipped at all .. look in container 2,

```
Scenario: Seeing 'Markdown' text format and toolbar as a Content Creator                                                                                                                # features/markdown_editor.feature:17
    Given I am logged in as "Gabriel"                                                                                                                                                     # Drupal\DrupalExtension\Context\DrupalContext::assertLoggedInByName()
    When I am on "Add Dataset" page                                                                                                                                                       # Drupal\DKANExtension\Context\PageContext::givenOnPage()
    Then I should have an "html" text format option                                                                                                                                       # Drupal\DKANExtension\Context\DKANContext::iShouldHaveAnTextFormatOption()
    And I should have an "plain_text" text format option                                                                                                                                  # Drupal\DKANExtension\Context\DKANContext::iShouldHaveAnTextFormatOption()
    And I should see the button "Make selected text into a header (Alt + H)" in the "dataset edit body"                                                                                   # Drupal\DrupalExtension\Context\MarkupContext::assertRegionButton()
    And I should see the button "Italics: Make selected text emphasized (Alt + I)" in the "dataset edit body"                                                                             # Drupal\DrupalExtension\Context\MarkupContext::assertRegionButton()
    And I should see the button "Bold: Make selected text strong (Alt + B)" in the "dataset edit body"                                                                                    # Drupal\DrupalExtension\Context\MarkupContext::assertRegionButton()
    And I should see the button "Format selected text as code" in the "dataset edit body"                                                                                                 # Drupal\DrupalExtension\Context\MarkupContext::assertRegionButton()
    And I should see the button "Format selected text as a code block" in the "dataset edit body"                                                                                         # Drupal\DrupalExtension\Context\MarkupContext::assertRegionButton()
    And I should see the button "Make selected text into a block quote (Alt + Q)" in the "dataset edit body"                                                                              # Drupal\DrupalExtension\Context\MarkupContext::assertRegionButton()
    And I should see the button "Make selected text into an ordered list (numbered) (Alt + O)" in the "dataset edit body"                                                                 # Drupal\DrupalExtension\Context\MarkupContext::assertRegionButton()
    And I should see the button "Make selected text into an unordered list (bullets) (Alt + N)" in the "dataset edit body"                                                                # Drupal\DrupalExtension\Context\MarkupContext::assertRegionButton()
    And I should see the button "Insert a definition list" in the "dataset edit body"                                                                                                     # Drupal\DrupalExtension\Context\MarkupContext::assertRegionButton()
    And I should see the button "Make text into an autolink (turns URLs in links, turns words into section identifiers for navigating the document) (Alt + A)" in the "dataset edit body" # Drupal\DrupalExtension\Context\MarkupContext::assertRegionButton()
    And I should see the button "Make text into a link (turns text into a link with more options) (Alt + L)" in the "dataset edit body"                                                   # Drupal\DrupalExtension\Context\MarkupContext::assertRegionButton()
    And I should see the button "Insert an image (Alt + M)" in the "dataset edit body"                                                                                                    # Drupal\DrupalExtension\Context\MarkupContext::assertRegionButton()
    And I should see the button "Insert a line break (Alt + R)" in the "dataset edit body"                                                                                                # Drupal\DrupalExtension\Context\MarkupContext::assertRegionButton()
    And I should see the button "Help" in the "dataset edit body"                                                                                                                         # Drupal\DrupalExtension\Context\MarkupContext::assertRegionButton()
    And I should not see the button "Insert a table" in the "dataset edit body"                                                                                                           # Drupal\DKANExtension\Context\DKANContext::iShouldNotSeeTheButtonInThe()
    And I should not see the button "Insert an abbreviation (word or acronym with definition)" in the "dataset edit body"                                                                 # Drupal\DKANExtension\Context\DKANContext::iShouldNotSeeTheButtonInThe()
    And I should not see the button "Insert a footnote" in the "dataset edit body"                                                                                                        # Drupal\DKANExtension\Context\DKANContext::iShouldNotSeeTheButtonInThe()
    And I should not see the button "Insert a horizontal ruler (horizontal line)" in the "dataset edit body"                                                                              # Drupal\DKANExtension\Context\DKANContext::iShouldNotSeeTheButtonInThe()
    And I should not see the button "Teaser break" in the "dataset edit body"                                                                                                             # Drupal\DKANExtension\Context\DKANContext::iShouldNotSeeTheButtonInThe()
````

**Comment by asghaier** [comment]
Oh, yes you are right I missed that.

Anyway the weird thing is that I tested on ProboCI and the button says:
"Make selected text into a header (Shift + Alt + H)"

And it used to fail on one of the builds on CircleCI, but now it says:
"Make selected text into a header (Alt + H)"

Not sure which one is correct. Maybe we should keep the last commit where we change the test to look only for:
"Make selected text into a header"
with no shortcut information.

Up to you @dkinzer and @janette if we should keep that change.

**Comment by janette** [comment]
New QA site at https://github.com/NuCivic/dkan/pull/1189

**Pull request closed without merging**
