### PR TITLE
Add field og group ref to the index when is enable the module dataset …

### PR DESCRIPTION
**Pull request by jacintocapote**
…groups in other case remove #621

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://bug_facet_blocks_tests_621.dkan.qa.nuamsdev.com

**Comment by jacintocapote** [comment]
Steps:
  * Go to http://bug_facet_blocks_tests_621.dkan.qa.nuamsdev.com/dataset
  * Check you can see facet publisher.
  * Check the test associated is passing.

**Comment by nucivicmachine** [comment]
QA site created: http://bug_facet_blocks_tests_621.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://bug_facet_blocks_tests_621.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://bug_facet_blocks_tests_621.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://bug_facet_blocks_tests_621.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://bug_facet_blocks_tests_621.dkan.qa.nuamsdev.com

**Pull request closed without merging**
