### PR TITLE
372 recline xls backend

### PR DESCRIPTION
**Pull request by acouch**
ref: #372 
### Acceptance test
- [ ] Manually add xls to test it is working
- [ ] Add test that uses an xls file

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://372_recline_xls_backend.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
@acouch On initial testing on the QA site, I'm not seeing this work for either XLS or XLSX files.

See:

http://372_recline_xls_backend.dkan.qa.nuamsdev.com/dataset/wisconsin-polling-places

**Comment by nucivicmachine** [comment]
QA site created: http://372_recline_xls_backend.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://372_recline_xls_backend.dkan.qa.nuamsdev.com

**Pull request closed without merging**
