### PR TITLE
Add list of visualizations to the resource page

### PR DESCRIPTION
**Pull request by janette**
## Issue

NuCivic/ok_data#197
Adds a list of visualizations to the resource page

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://197-visualizations-list-qa.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://197-visualizations-list-qa.dkan.qa.nuamsdev.com

**Comment by janette** [comment]
**This PR is dependent on another PR** https://github.com/NuCivic/dkan_dataset/pull/151

**Remove** changes to drupal-org.make

**Keep** changes to dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.pages_default.inc

**Comment by dafeder** [comment]
See NuCivic/dkan_dataset#151 for acceptance test

**Comment by nucivicmachine** [comment]
QA site created: http://197-visualizations-list-qa.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://197-visualizations-list-qa.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://197-visualizations-list-qa.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://197-visualizations-list-qa.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://197-visualizations-list-qa.dkan.qa.nuamsdev.com

**Pull request merged**
