### PR TITLE
Issue NuCivic/dkan#475: Home is repeated in Breadcrumbs

### PR DESCRIPTION
**Pull request by acouch**
ref: NuCivic/dkan#475
## Acceptance Test
- [x] Home not duplicated in breadcrumb

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://475-duplicated-home-breadcrumb.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://475-duplicated-home-breadcrumb.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://475-duplicated-home-breadcrumb.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://475-duplicated-home-breadcrumb.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://475-duplicated-home-breadcrumb.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
This updated PR moves ALL DKAN breadcrumb config into a single module with a README explaining the configuration.

**Comment by acouch** [comment]
Don't merge until hook_update_N included

**Comment by nucivicmachine** [comment]
QA site created: http://475-duplicated-home-breadcrumb.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://475-duplicated-home-breadcrumb.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://475-duplicated-home-breadcrumb.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://475-duplicated-home-breadcrumb.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
An update hook has been added to dkan_sitewide.

## Acceptance Test

- [ ] Home not duplicated in breadcrumb
- [ ] /dataset page breadcrumbs look right
- [ ] Breadcrumbs still work after upgrade from 7.x-1.x to this branch (dkan_sitewide_breadcrumbs is turned on)

**Comment by achraf-jeday** [comment]
I will refactor the layout.feature element search code into php in the feature content for a custom step "I should see a breadcrumb".

A breadcrumb step already exists in drupal context but it does not check breadcrumb order which is what we need.

Just hold for a day while i work on this.

**Comment by willieseabrook** [comment]
This is done now. With a new dedicated breadcrumb module and a very strong behat test this should is ready to merge.

**Comment by nucivicmachine** [comment]
QA site created: http://475-duplicated-home-breadcrumb.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://475-duplicated-home-breadcrumb.dkan.qa.nuamsdev.com

**Pull request closed without merging**
