### PR TITLE
DUMMY PR TO TEST POD 1.1

### PR DESCRIPTION
**Pull request by drkloc**
nuams/usda-nal#95

If the qa site data.json pass 1.1 validation, get NuCivic/open_data_schema_map#22 and NuCivic/open_data_schema_map_dkan#6 in and delete this PR

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://testing_pod_1_1.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
Something is wrong. Getting:

* Notice: Undefined index: pod_v1_1 in open_data_schema_map_schema_load() (line 369 of /var/www/dkan/testing_pod_1_1/profiles/dkan/modules/contrib/open_data_schema_map/open_data_schema_map.module).
* Warning: file_get_contents(): Filename cannot be empty in open_data_schema_map_schema_load() (line 371 of /var/www/dkan/testing_pod_1_1/profiles/dkan/modules/contrib/open_data_schema_map/open_data_schema_map.module).

And a bunch of stuff looks wrong in the JSON file.. missing catalog-level fields like "@id"

**Comment by acouch** [comment]
QA site created: http://testing_pod_1_1.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://testing_pod_1_1.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
So the POD validator is failing on a bunch of fields, mostly URLs. 

http://labs.data.gov/dashboard/validate?schema=federal-v1.1&output=browser&datajson_url=http%3A%2F%2Ftesting_pod_1_1.dkan.qa.nuamsdev.com%2Fdata.json&qa=true

@id - I am not sure, but I believe this is failing because there is no chartype specified in the Content-Type header. Should be specified as UTF-8

Distributions are also ALL failing. I have no idea why this is happening. I have poured over the spec and everything looks perfect.

**Comment by dafeder** [comment]
So the POD validator is failing on a bunch of fields, mostly URLs. 

http://labs.data.gov/dashboard/validate?schema=federal-v1.1&output=browser&datajson_url=http%3A%2F%2Ftesting_pod_1_1.dkan.qa.nuamsdev.com%2Fdata.json&qa=true

@id - I am not sure, but I believe this is failing because there is no chartype specified in the Content-Type header. Should be specified as UTF-8

Distributions are also ALL failing. I have no idea why this is happening. I have poured over the spec and everything looks perfect.

**Comment by acouch** [comment]
QA site created: http://testing_pod_1_1.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://testing_pod_1_1.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
@dafeder: I think the validator does not like urls with "_" in them like **testing_pod_1_1.dkan.qa.nuamsdev.com/data.json**.

I did the following:

+ Copy **http://testing_pod_1_1.dkan.qa.nuamsdev.com/data.json** output
+ Paste in a text editor
+ Replace **testing_pod_1_1** with **testing-pod-1-1**
+ Paste it under **Validate RAW json** at http://labs.data.gov/dashboard/validate
+ Click Validate JSON
+ You'll get output that json is valid
screen shot 2015-02-17 at 12 07 51 pm

**Comment by acouch** [comment]
QA site created: http://testing_pod_1_1.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://testing_pod_1_1.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
ref: #381

**Comment by drkloc** [comment]
closing this

**Pull request closed without merging**
