### PR TITLE
NuCivic/dkan#382 - Show notices only on available updates report.

### PR DESCRIPTION
**Pull request by msolv**
See: https://github.com/NuCivic/dkan/issues/382

### Acceptance test
- [x] Git pull
- [x] Rebuild a dkan instance.
- [x] Login 
- [x] Go through admin pages.
- [x] The messages about the 3 modules being up to date should only appear on /admin/reports/updates

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://nucivic_dkan_382_path_check_added.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://nucivic_dkan_382_path_check_added.dkan.qa.nuamsdev.com

**Comment by topicus** [comment]
screen shot 2015-02-25 at 11 34 01 am

**Comment by acouch** [comment]
QA site created: http://nucivic_dkan_382_path_check_added.dkan.qa.nuamsdev.com

**Pull request merged**
