### PR TITLE
411 move colorizer message to dkan sitewide

### PR DESCRIPTION
**Pull request by janette**
QA only

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://411_move_colorizer_message_to_dkan_sitewide.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://411_move_colorizer_message_to_dkan_sitewide.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://411_move_colorizer_message_to_dkan_sitewide.dkan.qa.nuamsdev.com

**Comment by janette** [comment]
1. go to QA site
2. log in and go to the appearance page:
http://411_move_colorizer_message_to_dkan_sitewide.dkan.qa.nuamsdev.com/admin/appearance
3. select a non-nuboot_radix theme for the admin theme
4. you should see a message with instructions for using colorizer.

**Comment by acouch** [comment]
QA site created: http://411_move_colorizer_message_to_dkan_sitewide.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
@janette this is good to go.

**Comment by acouch** [comment]
QA site created: http://411_move_colorizer_message_to_dkan_sitewide.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://411_move_colorizer_message_to_dkan_sitewide.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://411_move_colorizer_message_to_dkan_sitewide.dkan.qa.nuamsdev.com

**Pull request merged**
