### PR TITLE
Fixed problem with role default to administrator after new install #151

### PR DESCRIPTION
**Pull request by jacintocapote**
NuCivic/dkan#151

### CODE REVIEW

**Comment by jacintocapote** [comment]
Test [ ] Acces to environment a check that administrator is the default admin role.

**Comment by nucivicmachine** [comment]
QA site created: http://internal_151_admin_role_bug.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_151_admin_role_bug.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_151_admin_role_bug.dkan.qa.nuamsdev.com

**Pull request merged**
