### PR TITLE
Added date to index and to view story. #726

### PR DESCRIPTION
**Pull request by jacintocapote**
ref NuCivic/internal#726

### CODE REVIEW

**Comment by jacintocapote** [comment]
[ ] Check view story has the sort criteria based on node created date.

**Comment by nucivicmachine** [comment]
QA site created: http://internal_726_date_dkan_story.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_726_date_dkan_story.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_726_date_dkan_story.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_726_date_dkan_story.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_726_date_dkan_story.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_726_date_dkan_story.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_726_date_dkan_story.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_726_date_dkan_story.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_726_date_dkan_story.dkan.qa.nuamsdev.com

**Pull request merged**
