### PR TITLE
Sldata 11 hide unnecesary items in embed view

### PR DESCRIPTION
**Pull request by acouch**
DO NOT PULL QA ONLY

ref: https://github.com/NuCivic/recline/pull/23

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://sldata_11_hide_unnecesary_items_in_embed_view.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
this is already merged in dkan_dataset

**Comment by drkloc** [comment]
oh man, did i forget about this?

**Comment by acouch** [comment]
Works! http://sldata_11_hide_unnecesary_items_in_embed_view.dkan.qa.nuamsdev.com/node/5/recline-embed

**Comment by drkloc** [comment]
this is already merged on dkan_dataset. Closing.

**Pull request closed without merging**
