### PR TITLE
#670 Document search api upgrade problem

### PR DESCRIPTION
**Pull request by dafeder**
NuCivic/internal#844

## Acceptance test

1. Install DKAN at version 1.8
2. Upgrade to this version
3. It should be clear what needs to happen to fix search issue

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://670-dan-document-problem.dkan.qa.nuamsdev.com

**Comment by dkinzer** [comment]
@dafeder what is the upgrade directions... rerun make?

**Comment by dafeder** [comment]
You can look at NuCivic/internal#844 if you just want to see screenshots of what happens.

If you do want to try an upgrade, the steps I would follow would be something like

1. `git checkout tags/7.x-1.8`
3. `drush make build-dkan.make webroot`
3. `cd webroot && drush si dkan [...]`
4. `cd .. && cp -r webroot/sites ..`
5. `rm -rf webroot`
6. `git checkout 7.x-1.x`
7. `drush make build-dkan.make webroot`
8. `rm -rf webroot/sites && cp -r ../sites webroot`
9. `cd webroot`
10. `drush updb -y`
11. `drush fra -y`

**Comment by dkinzer** [comment]
Looks good!

**Comment by dkinzer** [comment]
Oh and thanks for the upgrade instructions.  Is this really what dkan users do to upgrade?  Looks tedious.

**Pull request merged**
