### PR TITLE
Update Social blocks

### PR DESCRIPTION
**Pull request by acouch**
## AC
- ~~Google plus is dead.~~
- [x] Linked in added
- [x] Reddit added

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://kill_google_plus.dkan.qa.nuamsdev.com

**Comment by akuckartz** [comment]
:-1:

**Comment by nucivicmachine** [comment]
QA site created: http://kill_google_plus.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://kill_google_plus.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://kill_google_plus.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://kill_google_plus.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://kill_google_plus.dkan.qa.nuamsdev.com

**Pull request merged**
