### PR TITLE
Freezing nuboot_radix to latest 7.x-1.x

### PR DESCRIPTION
**Pull request by msolv**
For QA only!

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://nucivic_nucivic_internal_471_upgrade_recline.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://nucivic_nucivic_internal_471_upgrade_recline.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://nucivic_nucivic_internal_471_upgrade_recline.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://nucivic_nucivic_internal_471_upgrade_recline.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://nucivic_nucivic_internal_471_upgrade_recline.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://nucivic_nucivic_internal_471_upgrade_recline.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://nucivic_nucivic_internal_471_upgrade_recline.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://nucivic_nucivic_internal_471_upgrade_recline.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://nucivic_nucivic_internal_471_upgrade_recline.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://nucivic_nucivic_internal_471_upgrade_recline.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
Waiting for tests and merging

**Comment by acouch** [comment]
QA site created: http://nucivic_nucivic_internal_471_upgrade_recline.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://nucivic_nucivic_internal_471_upgrade_recline.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
This is working as expected. Tests are passing. Merging.

**Comment by acouch** [comment]
QA site created: http://nucivic_nucivic_internal_471_upgrade_recline.dkan.qa.nuamsdev.com

**Pull request merged**
