### PR TITLE
Editor role permissions fix - rebase 2

### PR DESCRIPTION
**Pull request by dharizza**

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://762-editor-bugs-remake.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://762-editor-bugs-remake.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://762-editor-bugs-remake.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://762-editor-bugs-remake.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://762-editor-bugs-remake.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://762-editor-bugs-remake.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://762-editor-bugs-remake.dkan.qa.nuamsdev.com

**Comment by willieseabrook** [comment]
@dharizza Please review NuCivic/healthdata#437 and confirm that the new roles and permissions refactor means that this pull request should be closed without merging

**Comment by dharizza** [comment]
Hey @willieseabrook I've checked the file about the new DKAN permissions https://docs.google.com/spreadsheets/d/1JsDRSNbw56xsMq6UwjO_ZPIpQh_tMw0aTa5RgTqA80A/edit#gid=1845675830 and I think this PR is not longer needed and can be closed without merging.

**Comment by dharizza** [comment]
Sorry for my last comment, this is still on hold because this issues are still happening. I removed the reference to the role storyteller which is no longer necessary.

**Comment by dharizza** [comment]
Closing in favour of https://github.com/NuCivic/dkan_internal/issues/1

**Comment by nucivicmachine** [comment]
QA site created: http://762-editor-bugs-remake.dkan.qa.nuamsdev.com

**Pull request closed without merging**
