### PR TITLE
NuCivic/internal#745 Add theme preferences link to dashboard

### PR DESCRIPTION
**Pull request by dafeder**
Acceptance criteria

- [ ] Users with correct permissions can see theme preferences link and it points to correct URL for theme
- [ ] Tests pass

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://internal-745-theme-preferences2.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal-745-theme-preferences2.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal-745-theme-preferences2.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
Fixed in NuCivic/dkan#629

**Comment by nucivicmachine** [comment]
QA site created: http://internal-745-theme-preferences2.dkan.qa.nuamsdev.com

**Pull request closed without merging**
