### PR TITLE
Added patch to fontyourface

### PR DESCRIPTION
**Pull request by jacintocapote**
Fix problem with cache and fontyourface

ref #613

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://bug_fontface_add_new_rule_613.dkan.qa.nuamsdev.com

**Comment by jacintocapote** [comment]
Step to check:
  * Access to http://bug_fontface_add_new_rule_613.dkan.qa.nuamsdev.com/admin/appearance/fontyourface and use any font with any class and after save you should see the new font applied without clear cache.

**Comment by nucivicmachine** [comment]
QA site created: http://bug_fontface_add_new_rule_613.dkan.qa.nuamsdev.com

**Comment by stefaniefgray** [comment]
Tested steps from last comment left on #613 - still does not work properly

**Comment by nucivicmachine** [comment]
QA site created: http://bug_fontface_add_new_rule_613.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://bug_fontface_add_new_rule_613.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://bug_fontface_add_new_rule_613.dkan.qa.nuamsdev.com

**Pull request merged**
