### PR TITLE
Issue #590 Fix group pager

### PR DESCRIPTION
**Pull request by acouch**
ref #590
## Acceptance test

 - [x] You should be able to add more than 10 datasets to a single group and go to /groups and NOT see a pager for that group

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://590_group_page.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://590_group_page.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://590_group_page.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
Tests are passing so we can pull: https://github.com/NuCivic/dkan_dataset/pull/138

**Pull request merged**
