### PR TITLE
385 colorizer updates

### PR DESCRIPTION
**Pull request by janette**
Colorizer maintainer will not merge patches so updating make file.

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://385-colorizer-updates.dkan.qa.nuamsdev.com

**Comment by janette** [comment]
dependent on https://github.com/NuCivic/nuboot_radix/pull/10

**Comment by acouch** [comment]
QA site created: http://385-colorizer-updates.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://385-colorizer-updates.dkan.qa.nuamsdev.com

**Comment by janette** [comment]
**QA Review**
A change to the color scheme should be seen by anonymous users with out having to clear cache, and the front page hero photo should be tinted the correct color.

**Comment by drkloc** [comment]
Merging if tests passes and can review qa site with proposed criteria

**Comment by acouch** [comment]
QA site created: http://385-colorizer-updates.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
screen shot 2015-04-07 at 12 55 10 pm

Working. One test is failing for some reason. Rebasing into one commit.

**Comment by acouch** [comment]
QA site created: http://385-colorizer-updates.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://385-colorizer-updates.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
We're good to go. Merging.

**Pull request merged**
