### PR TITLE
#649 Restore public user page when looking at other users

### PR DESCRIPTION
**Pull request by dafeder**
ref #649 

Acceptance test:

Create second user, "test."

- [x] Admin should be able to see users/test page for that user
- [x] Admin should be able to see user command center
- [x] Anonymous should see normal user page for both admin and test user

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://649-dan-user-page.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
http://649-dan-user-page.dkan.qa.nuamsdev.com/users/admin
http://649-dan-user-page.dkan.qa.nuamsdev.com/users/test

**Comment by nucivicmachine** [comment]
QA site created: http://649-dan-user-page.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://649-dan-user-page.dkan.qa.nuamsdev.com

**Pull request merged**
