### PR TITLE
Patch for panopoly spotlight widget

### PR DESCRIPTION
**Pull request by drkloc**
NuCivic/internal#759: Adds patch to explicitly add jquery.ui.tabs.js from jquery_update module

### Acceptance Criteria

- [x] Behat tests for spotlight widget should pass

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://internal_759_spotlight_widget_test.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
screen shot 2015-08-06 at 11 26 50 am

https://travis-ci.org/NuCivic/dkan/builds/74411712#L1259

Spotlight Tests passing ^^^

**Comment by nucivicmachine** [comment]
QA site created: http://internal_759_spotlight_widget_test.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_759_spotlight_widget_test.dkan.qa.nuamsdev.com

**Pull request merged**
