### PR TITLE
Issue #656 removes dataset list from panel page and restores Resource blocks

### PR DESCRIPTION
**Pull request by acouch**
ref: #656 

# AC

- [x] Dataset list not on about or resource pages.
- [x] Resource list and additional issue are restored are Resource page

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://656_removes_dataset_list.dkan.qa.nuamsdev.com

**Comment by janette** [comment]
@acouch this seems to be removing several permissions from the og 'member' role and removes the date changed sort order on the search view
screenshot_8_21_15__8_21_pm

**Comment by acouch** [comment]
The date was previously removed and is showing up with the updated export. Lets try again.

**Comment by acouch** [comment]
It looks like this doesn't add the broken message. I re-added the "Addtional Info" block. If this passes will include that in a test.

**Comment by nucivicmachine** [comment]
QA site created: http://656_removes_dataset_list.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://656_removes_dataset_list.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
This works and is passing however the resource list needs some theming:

screen shot 2015-08-23 at 2 27 25 pm

Maybe http://getbootstrap.com/components/#list-group ?

It would be easy to switch to bootstraps list-group which would look like this since list-group is overridden and basically removed in nuboot-radix:

screen shot 2015-08-23 at 2 29 44 pm

Also ``active`` class isn't acknowledged in the CSS. Can we pull this in and have a separate fix for the Resource list theming?

**Comment by nucivicmachine** [comment]
QA site created: http://656_removes_dataset_list.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://656_removes_dataset_list.dkan.qa.nuamsdev.com

**Comment by janette** [comment]
@acouch is the only hang up on merging this the theming?

**Comment by dafeder** [comment]
@acouch please clarify - what does the resource list have to do with the scope of this ticket?

**Comment by nucivicmachine** [comment]
QA site created: http://656_removes_dataset_list.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://656_removes_dataset_list.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://656_removes_dataset_list.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
> Can we pull this in and have a separate fix for the Resource list theming?

@janette I'm not saying it is a blocker

**Comment by Krista-Nuams** [comment]
Aaron will pull this and make a separate ticket about the Resource theming (i.e. if you scroll down past the preview here http://656_removes_dataset_list.dkan.qa.nuamsdev.com/dataset/wisconsin-polling-places/resource/7f2b5b57-88e3-42e2-90d4-21b060d4f432)

**Comment by nucivicmachine** [comment]
QA site created: http://656_removes_dataset_list.dkan.qa.nuamsdev.com

**Pull request merged**
