### PR TITLE
Civic-2251 Fixing composer cache for Circle CI

### PR DESCRIPTION
**Pull request by asghaier**
Branch based on tag 7.x-1.12

### CODE REVIEW

**Comment by asghaier** [comment]
DO NOT MERGE
No longer required for related repositories (site repositories and module repositories) to run Circle CI tests and build Probo CI test sites.

**Comment by asghaier** [comment]
This should be safe to merge.
This specifically fixes upgrading Drush version to a newer version.
It removes the composer folder in the home directory .composer and .config/composer to make sure all Drush dependencies gets pulled and are fresh (This way we can avoid having complex dependencies conflicts)

**Comment by dkinzer** [comment]
@dafeder this is touching more than just devops stuff... I can't merge this.

@asghaier is this a mistake?  Did you mean to create a PR with all these non devops changes?

**Comment by dafeder** [comment]
I believe this branch was created incorrectly - it should have the same diff as #1078, right? Since the branch happened way too late to be merged safely back into the release branch, you should create a new branch off of `release-1-9` and just cherry-pick the relevant commits.

**Comment by drkloc** [comment]
recreating this against 7.x-1.x

**Pull request closed without merging**
