### PR TITLE
WIP: Fix ahoy site reinstall backups.

### PR DESCRIPTION
**Pull request by dkinzer**
REF CIVIC-2918

This issue seems to only be affecting Dan.  However since we have been having
issues with getting commands to run when && is supplied to ahoy bash I've
removed that and instead have made an explicit check to do the backup.

@dafeder since you are the only one (so far) experiencing this issue, can you
please QA this when you get a chance.  If it fails please post the entire
output of `ahoy --verbose reintall`. Thanks!!!

AC
==
* `ahoy site reinstall` creates a backup.

### CODE REVIEW

**Comment by dkinzer** [comment]
@dafeder have you had a chance to see if this PR fixes your issue?

**Comment by dafeder** [comment]
@dkinzer this did not fix it for me. Thanks for trying, no idea what's wrong.

**Comment by dkinzer** [comment]
Let's close this for now.. ahoy tools are getting a makeover .. we'll revisit (soon others could have same issue)

**Comment by dkinzer** [comment]
Closing in favor of #1436

**Pull request closed without merging**
