### PR TITLE
Panopoly widge

### PR DESCRIPTION
**Pull request by acouch**
DO NOT PULL. FOR QA ONLY!

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
Still playing with this.

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://panopoly_widge.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
this was introduced in #493 

Closing.

**Pull request closed without merging**
