### PR TITLE
Update drupal-org.make

### PR DESCRIPTION
**Pull request by janette**
QA Only - do not merge

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://559-exposed-view-labels.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://559-exposed-view-labels.dkan.qa.nuamsdev.com

**Comment by jacintocapote** [comment]
Working perfect

**Comment by nucivicmachine** [comment]
QA site created: http://559-exposed-view-labels.dkan.qa.nuamsdev.com

**Pull request closed without merging**
