### PR TITLE
Add user command center

### PR DESCRIPTION
**Pull request by topicus**
Don't merge this. Only for QA purposes.

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://internal_580_user_command_center.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
ref NuCivic/internal#580

**Comment by dafeder** [comment]
Closing, creating new PR against release branch

**Comment by nucivicmachine** [comment]
QA site created: http://internal_580_user_command_center.dkan.qa.nuamsdev.com

**Pull request closed without merging**
