### PR TITLE
Validate json input leaflet draw widget2

### PR DESCRIPTION
**Pull request by acouch**
Trying to get https://github.com/NuCivic/dkan/pull/647 to pass. Not sure why that wasn't passing tests.

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://validate_json_input_leaflet_draw_widget2.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://validate_json_input_leaflet_draw_widget2.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://validate_json_input_leaflet_draw_widget2.dkan.qa.nuamsdev.com

**Comment by kimwdavidson** [comment]
Merged. Closing.

**Pull request closed without merging**
