### PR TITLE
Search page redesign: new collapsible sidebar facets with icons, new …

### PR DESCRIPTION
**Pull request by asghaier**
…search page teaser with icons and no count

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
Depends on 
* NuCivic/nuboot_radix#49
* NuCivic/dkan_dataset#188

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://661-search-page-redesign.dkan.qa.nuamsdev.com

**Pull request merged**
