### PR TITLE
630 increase font size

### PR DESCRIPTION
**Pull request by janette**
Testing NuBoot Radix updates for NuCivic/internal#630
related updates
~~https://github.com/NuCivic/dkan_dataset/pull/119~~ Pulled
~~https://github.com/NuCivic/field_group_table/pull/1~~ Pulled

QA ONLY - do not pull

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://630-increase-font-size.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://630-increase-font-size.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://630-increase-font-size.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://630-increase-font-size.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://630-increase-font-size.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://630-increase-font-size.dkan.qa.nuamsdev.com

**Pull request closed without merging**
