### PR TITLE
Issue #173 Test @asghaier zip download for dkan_dataset

### PR DESCRIPTION
**Pull request by dafeder**
- [ ] A dataset with multiple resources can be downloaded as a single zip

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://173-asghaier-zip.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
Checking the QA site, noticed the following issues that need to be addressed. 

- [ ] Files from unpublished datasets still included in ZIP
- [ ] "Download all" link provided even when just one file is available (but maybe this is  desirable? Consulting with UX people)

**Comment by acouch** [comment]
QA site created: http://173-asghaier-zip.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://173-asghaier-zip.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://173-asghaier-zip.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://173-asghaier-zip.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
This was merged upstream.

**Comment by nucivicmachine** [comment]
QA site created: http://173-asghaier-zip.dkan.qa.nuamsdev.com

**Pull request closed without merging**
