### PR TITLE
Panopoly widget

### PR DESCRIPTION
**Pull request by topicus**
This PR adds all the panopoly widgets to dkan.

### Acceptance test
- [x]  Pass the widget.feature tests

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://panopoly_widget.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
rebasing

**Comment by acouch** [comment]
QA site created: http://panopoly_widget.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
this is working, waiting for tests to pass and merging NuCivic/internal#453

**Comment by acouch** [comment]
QA site created: http://panopoly_widget.dkan.qa.nuamsdev.com

**Pull request merged**
