### PR TITLE
Added right permission for dkan featured #538

### PR DESCRIPTION
**Pull request by jacintocapote**
ref NuCivic/dkan#538

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://internal_538_groups_permissions.dkan.qa.nuamsdev.com

**Comment by jacintocapote** [comment]
Test access to http://internal_538_groups_permissions.dkan.qa.nuamsdev.com/admin/structure/views/view/dkan_groups_featured/edit/panel_pane_1 and check that the permission on the view is view published content

**Comment by dafeder** [comment]
Covered in NuCivic/dkan#569

**Comment by nucivicmachine** [comment]
QA site created: http://internal_538_groups_permissions.dkan.qa.nuamsdev.com

**Pull request closed without merging**
