### PR TITLE
464 508 compliance

### PR DESCRIPTION
**Pull request by janette**
QA -  testing 508 updates to dkan_dataset, dkan_sitewide, and nuboot_radix

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://464-508-compliance.dkan.qa.nuamsdev.com

**Comment by janette** [comment]
**QA Review**
Front page:
- [ ] Search field in header and hero section should not be flagged for no labels
- [ ] Add Data block in the hero section should not be flagged for a link with empty text. 

Dataset page:

- [ ] the download button should not be flagged for being a link with empty text

Search page:

- [ ] the exposed view text field should not be flagged for no label

Nuboot Radix
- [ ]  labels for the search, exposed view and download should be hidden.

**Comment by acouch** [comment]
QA site created: http://464-508-compliance.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://464-508-compliance.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://464-508-compliance.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://464-508-compliance.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://464-508-compliance.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://464-508-compliance.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://464-508-compliance.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://464-508-compliance.dkan.qa.nuamsdev.com

**Pull request merged**
