### PR TITLE
Behat test for filtered dataset view pane on dashboards

### PR DESCRIPTION
**Pull request by drkloc**
NuCivic/internal#618

### Acceptance criteria

- [x] Tests for filtered dataset view on data_dashboard.feature should run and pass.

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://618_add_configuration_to_view_panes.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://618_add_configuration_to_view_panes.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://618_add_configuration_to_view_panes.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://618_add_configuration_to_view_panes.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
Test are passing:
screen shot 2015-08-07 at 11 21 01 am

https://travis-ci.org/NuCivic/dkan/builds/74491621#L1380

**Comment by nucivicmachine** [comment]
QA site created: http://618_add_configuration_to_view_panes.dkan.qa.nuamsdev.com

**Pull request merged**
