### PR TITLE
updated colorize to 1.7  #641

### PR DESCRIPTION
**Pull request by jacintocapote**
ref NuCivic/internal#641

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://internal_641_colorize_problem.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_641_colorize_problem.dkan.qa.nuamsdev.com

**Comment by jacintocapote** [comment]
Steps for test:
  1.- Access first time with anonymous and you should see the same that authenticated user (color, navbar color, ...)
  2.- Enable caching page.
  3.- Do any change on colorize (background header, nav, ...) and save.
  4.- Check with anonymous colors are fine.

**Comment by dafeder** [comment]
screen shot 2015-07-20 at 12 40 15 pm

Does not appear to work

**Comment by nucivicmachine** [comment]
QA site created: http://internal_641_colorize_problem.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_641_colorize_problem.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_641_colorize_problem.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_641_colorize_problem.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_641_colorize_problem.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_641_colorize_problem.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_641_colorize_problem.dkan.qa.nuamsdev.com

**Pull request merged**
