### PR TITLE
447 hook implementation to add remove licenses options

### PR DESCRIPTION
**Pull request by acouch**
Adds tests for updated license.

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://447_hook_implementation_to_add_remove_licenses_options.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://447_hook_implementation_to_add_remove_licenses_options.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://447_hook_implementation_to_add_remove_licenses_options.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://447_hook_implementation_to_add_remove_licenses_options.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://447_hook_implementation_to_add_remove_licenses_options.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://447_hook_implementation_to_add_remove_licenses_options.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://447_hook_implementation_to_add_remove_licenses_options.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://447_hook_implementation_to_add_remove_licenses_options.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
please rebase :smile:

**Comment by acouch** [comment]
QA site created: http://447_hook_implementation_to_add_remove_licenses_options.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://447_hook_implementation_to_add_remove_licenses_options.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
Superseded by #2123

**Pull request closed without merging**
