### PR TITLE
Limit Row Length for Tables on Dataset Page

### PR DESCRIPTION
**Pull request by acouch**
Adds:
screen shot 2015-08-14 at 4 30 12 am

Do not pull, for QA only.

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://limit_table_row_length.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
See: http://limit_table_row_length.dkan.qa.nuamsdev.com/dataset/wisconsin-polling-places

**Comment by nucivicmachine** [comment]
QA site created: http://limit_table_row_length.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://limit_table_row_length.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
PR that actually needs merging: NuCivic/dkan_dataset#140

**Comment by nucivicmachine** [comment]
QA site created: http://limit_table_row_length.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://limit_table_row_length.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://limit_table_row_length.dkan.qa.nuamsdev.com

**Comment by SalahMessaoud** [comment]
@acouch I built this locally it, the fix doesn't exist in the `limit_table_row_length` branch, the fix is at https://github.com/NuCivic/dkan_dataset/pull/140/

**Pull request closed without merging**
