### PR TITLE
7.x 1.x feedback implementation

### PR DESCRIPTION
**Pull request by dafeder**

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://7.x-1.x_feedback_implementation.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://7.x-1.x_feedback_implementation.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://7.x-1.x_feedback_implementation.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
Postponing this for now

**Pull request closed without merging**
