### PR TITLE
116 user photo

### PR DESCRIPTION
**Pull request by janette**
Updates to dkan_sitewide_roles_perms for user photo

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://116-user-photo.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://116-user-photo.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://116-user-photo.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://116-user-photo.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://116-user-photo.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://116-user-photo.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
this passed test. Merging.

**Pull request merged**
