### PR TITLE
Adds modules to quickly deploy to acquia

### PR DESCRIPTION
**Pull request by drkloc**
Issue #572

WORK IN PROGRESS DO NOT MERGE

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://572_acquia_modules.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://572_acquia_modules.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://572_acquia_modules.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://572_acquia_modules.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
Discussed this with @acouch and we are setting an upstream

**Pull request closed without merging**
