### PR TITLE
Creating demo site

### PR DESCRIPTION
**Pull request by topicus**
DON'T PULL THIS. ONLY FOR QA ;-)

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://viz_entity_charts_demo.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://viz_entity_charts_demo.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://viz_entity_charts_demo.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://viz_entity_charts_demo.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://viz_entity_charts_demo.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://viz_entity_charts_demo.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://viz_entity_charts_demo.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://viz_entity_charts_demo.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://viz_entity_charts_demo.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
it's been a month. Closing.

**Pull request closed without merging**
