### PR TITLE
Added adminrole to main makefile #534

### PR DESCRIPTION
**Pull request by jacintocapote**
NuCivic/dkan#534

### CODE REVIEW

**Comment by jacintocapote** [comment]
- [ ] Check adminrole is added is a fresh install and administrator role is assigned by default

**Comment by nucivicmachine** [comment]
QA site created: http://internal_534_install_adminrole.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_534_install_adminrole.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_534_install_adminrole.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_534_install_adminrole.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_534_install_adminrole.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_534_install_adminrole.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_534_install_adminrole.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_534_install_adminrole.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://internal_534_install_adminrole.dkan.qa.nuamsdev.com

**Pull request merged**
