### PR TITLE
617 featured groups

### PR DESCRIPTION
**Pull request by janette**
QA only - do not pull

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://617-featured-groups.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://617-featured-groups.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://617-featured-groups.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://617-featured-groups.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://617-featured-groups.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
NuCivic/internal#617

**Comment by acouch** [comment]
QA site created: http://617-featured-groups.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://617-featured-groups.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
### Acceptance Test

**Add the new view**
- [ ] log in
- [ ] click 'customize this page' on the front page
- [ ] click the plus sign to add a new pane to the middle row
- [ ] click views
- [ ] click Add on the 'DKAN Groups featured' panel
- [ ] select the featured group grid display
- [ ] click continue
- [ ] click finish

**Change the order of groups**
- [ ] from the admin menu, navigate to DKAN > Featured Groups Sort Order
- [ ] drag the groups to the order you wish
- [ ] click save
- [ ] view changes on the front page

**Comment by drkloc** [comment]
This is working properly. Waiting for tests to pass and merging.

**Pull request merged**
