### PR TITLE
Fixed issue: font is still used after being disabled (CIVIC-512).

### PR DESCRIPTION
**Pull request by achraf-jeday**
NOTE: Continued here: https://github.com/NuCivic/dkan/pull/865

ref https://jira.govdelivery.com/browse/CIVIC-512
### Acceptance
1. Go to 'admin/appearance/fontyourface/browse/google_fonts_api'.
2. Enable a font, any font.
3. Go to "Enabled fonts" tab.
4. Choose "Everything (Body)" from the font CSS selector dropdown list.
5. Save.
6. Go to "Browse Fonts" tab and disable the font.
7. Reload the page, drupal default font should be used on the page.

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://CIVIC_512_font_still_in_use_after_being_disabled.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://CIVIC_512_font_still_in_use_after_being_disabled.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://CIVIC_512_font_still_in_use_after_being_disabled.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://CIVIC_512_font_still_in_use_after_being_disabled.dkan.qa.nuamsdev.com

**Comment by janette** [comment]
Fix was merged here https://github.com/NuCivic/dkan/pull/865, closing as duplicate

**Pull request closed without merging**
