### PR TITLE
Dev dkan ahoy smarter

### PR DESCRIPTION
**Pull request by frankcarey**

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://dev-dkan-ahoy-smarter.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://dev-dkan-ahoy-smarter.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://dev-dkan-ahoy-smarter.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://dev-dkan-ahoy-smarter.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://dev-dkan-ahoy-smarter.dkan.qa.nuamsdev.com

**Comment by frankcarey** [comment]
Double checked, and the components of this PR have already been merged.

**Pull request closed without merging**
