### PR TITLE
Fix Cross-site scripting (XSS) vulnerability #790

### PR DESCRIPTION
**Pull request by topicus**
It fixes NuCivic/dkan#790

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://issue_790.dkan.qa.nuamsdev.com

**Comment by topicus** [comment]
It seems to be working properly:

screen shot 2016-01-04 at 5 23 28 pm

**Comment by nucivicmachine** [comment]
QA site created: http://issue_790.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://issue_790.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
You can see this vulnerability by:

1. Enabling the module
2. Create a search page with facets
3. Then you can inject scripts through url params: http://example.com/search-page?f[0]=field_tags:<script>alert(512)</script>
4. Modern browsers like chrome refuses to execute this script because it's in the url but old ones like IE7 executes the alert.

**Comment by dafeder** [comment]
Also fixes #791 and #792

**Pull request merged**
