### PR TITLE
NuCivic/internal#618 Add filterable dataset view pane option

### PR DESCRIPTION
**Pull request by janette**
ref NuCivic/internal#618

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://618-filtered-dataset-pane-2.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://618-filtered-dataset-pane-2.dkan.qa.nuamsdev.com

**Comment by janette** [comment]
documentation: http://docs.getdkan.com/dkan-documentation/dkan-users-guide/customize-dkan-pages-layouts-and-components-using-panels#Dataset_list_filtered_by_group_andor_tag

This commit adds a new panel option for displaying a list of datasets

- [ ] From the home page, or any other panelized page, click the 'Customize this page' button
- [ ] Select the region where you want to add the dataset list, and click the upper left gear and select 'Add Content’.

- [ ] On the overlay that appears, select the ‘View panes’ category on the left, then click the ‘+Add’ button on the Custom Filtered Dataset List option.

- [ ] The next screen show the settings for the panel. You can set a custom title, set the pager, filter by group or by tag. Click ‘Finish’ to save.

- [ ] Then click the ‘Update and save’ on the panel configuration screen.

**Comment by nucivicmachine** [comment]
QA site created: http://618-filtered-dataset-pane-2.dkan.qa.nuamsdev.com

**Pull request merged**
