### PR TITLE
Recreate view members for dataset

### PR DESCRIPTION
**Pull request by jacintocapote**
Recreate view members on dataset nodes to show the right information

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://view_members_for_dataset_nodes_884.dkan.qa.nuamsdev.com

**Comment by jacintocapote** [comment]
Steps for test:
  1.- Access to any dataset for example http://view_members_for_dataset_nodes_884.dkan.qa.nuamsdev.com/node/4/members
  2.- You should see only 1 time admin user.
  3.- Add a new user to the group and with some role.
  4.- Check is showed and on the list.

**Comment by nucivicmachine** [comment]
QA site created: http://view_members_for_dataset_nodes_884.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://view_members_for_dataset_nodes_884.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://view_members_for_dataset_nodes_884.dkan.qa.nuamsdev.com

**Pull request closed without merging**
