### PR TITLE
Adding honeypot to dkan

### PR DESCRIPTION
**Pull request by drkloc**
NuCivic/dkan#341
NuCivic/nucivic-internal#160

### Acceptance Test

- [x] Go to admin/config/content/honeypot
- [x] User Registration form should be checked

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://341_add_honeypot_to_dkan.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://341_add_honeypot_to_dkan.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
this need behat tests to make sure honeypot is enabled

**Comment by acouch** [comment]
QA site created: http://341_add_honeypot_to_dkan.dkan.qa.nuamsdev.com

**Pull request merged**
