### PR TITLE
QA for chosen module and libraries updates

### PR DESCRIPTION
**Pull request by drkloc**
DO NOT MERGE

### CODE REVIEW

**Comment by drkloc** [comment]
running test again with fixed chosen version -> https://github.com/NuCivic/dkan_dataset/pull/130/files

**Comment by nucivicmachine** [comment]
QA site created: http://drkloc-patch-1.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://drkloc-patch-1.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://drkloc-patch-1.dkan.qa.nuamsdev.com

**Pull request closed without merging**
