### PR TITLE
Validate json input leaflet draw widget

### PR DESCRIPTION
**Pull request by jacintocapote**

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://validate_json_input_leaflet_draw_widget.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://validate_json_input_leaflet_draw_widget.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://validate_json_input_leaflet_draw_widget.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://validate_json_input_leaflet_draw_widget.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://validate_json_input_leaflet_draw_widget.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://validate_json_input_leaflet_draw_widget.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://validate_json_input_leaflet_draw_widget.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://validate_json_input_leaflet_draw_widget.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://validate_json_input_leaflet_draw_widget.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
If tests pass we should push https://github.com/NuCivic/dkan_dataset/pull/141

**Comment by nucivicmachine** [comment]
QA site created: http://validate_json_input_leaflet_draw_widget.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://validate_json_input_leaflet_draw_widget.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://validate_json_input_leaflet_draw_widget.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://validate_json_input_leaflet_draw_widget.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://validate_json_input_leaflet_draw_widget.dkan.qa.nuamsdev.com

**Pull request closed without merging**
