### PR TITLE
Ahoy command to create subtheme from kit

### PR DESCRIPTION
**Pull request by drkloc**
#CIVIC-1956

# Usage

```
$ ahoy dkan theme new-from-kit <theme_name>
```

It should:

- [x] Validate that it receives an argument
- [x] Output error message if trying to create a theme with the same name of an existing theme present in the `sites/all/themes` folder
- [ ] Output error message if it can't reach `https://github.com/NuCivic/radix-kit-nuboot/archive/master.zip`
- [x] Succesfully create a theme from nuboot at `sites/all/themes` 
- [x] Able to compile css on custom theme
- [x] Able to compile css on nuboot radix

### CODE REVIEW

**Comment by janette** [comment]
@drkloc this works great for creating the subtheme, can we add two additional steps after the theme is created
1. `drush vset theme_default {new theme machine name}`
2. `drush pm-disable nuboot_radix`

Also we need a way to compile changes on this theme, can the existing commands be updated to work on any theme as long as you are in the theme directory? so running from /dkan/themes/nuboot_radix works for nuboot_radix and running from docroot/sites/all/themes/custom_theme works on that theme?

**Comment by drkloc** [comment]
sure

**Comment by drkloc** [comment]
@janette ready for review

**Comment by janette** [comment]
@drkloc this is wonderful!!

One small hitch is that the new theme is not enabled automatically.

dkan_ _bash_ _192x37_and_appearance___dkan

banners_and_alerts_and_appearance___dkan

Maybe we need to run the 'save configuration' on form id `system_themes_admin_form`...?

**Comment by janette** [comment]
@drkloc ready for review :)

**Comment by janette** [comment]
@drkloc do you want me to merge this? or you want to verify my changes?

**Pull request merged**
