### PR TITLE
#552 Test new chosen vars in dkan_dataset

### PR DESCRIPTION
**Pull request by dafeder**
DO NOT MERGE

- [ ] Tests should pass
- [ ] Chosen should show up on dataset form with just the default content

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://552-chosen-vars.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://552-chosen-vars.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
pulls in changes in NuCivic/dkan_dataset#131

**Comment by nucivicmachine** [comment]
QA site created: http://552-chosen-vars.dkan.qa.nuamsdev.com

**Pull request closed without merging**
