### PR TITLE
Fixed problem with svgeezy #706

### PR DESCRIPTION
**Pull request by jacintocapote**

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://internal_706_bug_svgeezy.dkan.qa.nuamsdev.com

**Comment by jacintocapote** [comment]
For test "Download a VM from http://dev.modern.ie/tools/vms/ with IE8 and go to http://internal_706_bug_svgeezy.dkan.qa.nuamsdev.com apparence -> uncheck use default logo and see that you are using svg logo. Then check on IE8 if you can see the logo"

**Comment by dafeder** [comment]
QA only. Fixed upstream. Closing.

**Comment by nucivicmachine** [comment]
QA site created: http://internal_706_bug_svgeezy.dkan.qa.nuamsdev.com

**Pull request closed without merging**
