### PR TITLE
NuCivic/internal#630 Update radix theme to fix panel templates

### PR DESCRIPTION
**Pull request by janette**
Related to https://github.com/NuCivic/internal/issues/630

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://630-internal-update-radix.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://630-internal-update-radix.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
Did this in commits directly to 1.9-release

**Comment by nucivicmachine** [comment]
QA site created: http://630-internal-update-radix.dkan.qa.nuamsdev.com

**Pull request closed without merging**
