### PR TITLE
fixed translation function

### PR DESCRIPTION
**Pull request by takuya310**
Add translation function for 'About', 'Add Dataset', 'Groups'.

### CODE REVIEW

**Comment by nuamsmachine** [comment]
Can one of the admins verify this patch?

**Comment by nuamsmachine** [comment]
Can one of the admins verify this patch?

**Comment by takuya310** [comment]
Add translation function, again.

**Comment by dafeder** [comment]
Closing - these are on feature exports so will be overwritten every time feature is exported. Supporting good i18n is clearly still a big todo but we should do according to Drupal best practice.

**Pull request closed without merging**
