### PR TITLE
Editor Bugs

### PR DESCRIPTION
**Pull request by drkloc**
NuCivic/internal#762

Rebased version of #632

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://762-editor-bugs-rebased.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://762-editor-bugs-rebased.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
Think  we have this covered in #636

**Comment by nucivicmachine** [comment]
QA site created: http://762-editor-bugs-rebased.dkan.qa.nuamsdev.com

**Pull request closed without merging**
