### PR TITLE
547 resource redirect

### PR DESCRIPTION
**Pull request by acouch**
Issue #547 

This is for tests and QA only.

The following is added to `dkan_dataset.module`

```
 /**
+ * Implements hook_node_insert().
+ */
+function dkan_dataset_node_insert($node) {
+  switch ($node->type) {
+    case 'resource':
+      if (isset($node->field_dataset_ref['und'][0]) && $node->op == 'Save') {
+        $dataset_nid = $node->field_dataset_ref['und'][0]['target_id'];
+        $dataset_node = node_load($dataset_nid);
+        $dataset_wrapper = entity_metadata_wrapper('node', $dataset_node);
+        // Save resource on dataset before redirect.
+        $dataset_wrapper->field_resources->set(array($node->nid));
+        $dataset_wrapper->save();
+        // Redirect to the dataset after saving the last node in the form.
+        drupal_goto('node/' . $dataset_nid);
+      }
+    break;
+  }
+}
```

It checks for the `op` parameter so does not redirect on non-form saves.

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://547_resource_redirect.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
When passing, merge NuCivic/dkan_dataset#143

**Comment by nucivicmachine** [comment]
QA site created: http://547_resource_redirect.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://547_resource_redirect.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://547_resource_redirect.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
The tests pass (https://travis-ci.org/NuCivic/dkan/builds/76739829) so I rewrote the history. Now the local commit is just test changes. So this should be pulled with https://github.com/NuCivic/dkan_dataset/pull/143

Maybe we should move to commit messages with dkan_dataset instead of the dev branch.

**Comment by nucivicmachine** [comment]
QA site created: http://547_resource_redirect.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://547_resource_redirect.dkan.qa.nuamsdev.com

**Pull request closed without merging**
