### PR TITLE
NuCivic/internal#821 Consistent Roles and Permissions export.

### PR DESCRIPTION
**Pull request by rhabbachi**
Ref: NuCivic/internal#821, NuCivic/internal#776

* Export All DKAN Core roles (Anonymous, Authenticated, Editor, Administrator)
 into new dkan_permissions feature.
* Add *Site Manager* to replace *Portal Administrator* Role.
* Data Contributor in the DKAN Spreadsheet is dropped in favor of separate
 contributor/approver/supervisor roles provided by the [DKAN
 Workflow](https://github.com/NuCivic/dkan_workflow).
* Bump features_roles_permissions to 1.2 to be able to export authenticated and
 anonymous user.

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://821_unblock_roles.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
@rhabbachi are you able to write acceptance tests for this?

**Comment by rhabbachi** [comment]
@dafeder We only renamed/exported current roles so the only thing to do is to change "Protal Administrator" with "Site Administrator".

**Comment by rhabbachi** [comment]
@dafeder Turn out that right now we don't have any specific tests for the "Portal Administrator" role so in the end no action is needed.

**Comment by dafeder** [comment]
@rhabbachi is there a reason that dkan.info wasn't changed? I think the idea was to make sure it was enabled on new installations going forward...

**Comment by rhabbachi** [comment]
@dafeder Actually you raised the issue that we wanted an upgrade path for other non Nucivic users that wants to upgrade their in production Dkan based sites IIRC.

I think some of the work related to the upgrade path was done by @dkinzer for HHS. Specifically the users roles migration.

**Comment by nucivicmachine** [comment]
QA site created: http://821_unblock_roles.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://821_unblock_roles.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://821_unblock_roles.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://821_unblock_roles.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://821_unblock_roles.dkan.qa.nuamsdev.com

**Pull request merged**
