### PR TITLE
534 user admin role set

### PR DESCRIPTION
**Pull request by dafeder**
## Acceptance test

User admin role is set on install.

### CODE REVIEW

**Comment by dafeder** [comment]
So....

**Comment by nucivicmachine** [comment]
QA site created: http://534-user-admin-role-set.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://534-user-admin-role-set.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://534-user-admin-role-set.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://534-user-admin-role-set.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://534-user-admin-role-set.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://534-user-admin-role-set.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://534-user-admin-role-set.dkan.qa.nuamsdev.com

**Comment by dafeder** [comment]
Tests are totally brittle at this point. I super simplified the one that was failing but still only seem to pass about half the time :S

**Comment by nucivicmachine** [comment]
QA site created: http://534-user-admin-role-set.dkan.qa.nuamsdev.com

**Pull request merged**
