### PR TITLE
618 filtered dataset pane

### PR DESCRIPTION
**Pull request by janette**
NuCivic/internal#618

### Acceptance Test

- [x] Log in
- [x] Navigate to a page where you would like to add a list of datasets
- [x] Click the 'Edit Panel' gear on the top right corner of the content section
- [x] Click the 'Add content' link on the region you would like to add the list to
- [x] Click on 'View Panes' from the left side options
- [x] Click '+Add' next to **View: DKAN Datasets Filtered: Custom Filtered Dataset List**
- [x] Adjust the title, pager use, tags, and/or group filters and click 'Finish'
- [x] Enjoy your custom filtered list of datasets

### CODE REVIEW

**Comment by acouch** [comment]
QA site created: http://618-filtered-dataset-pane.dkan.qa.nuamsdev.com

**Comment by janette** [comment]
@federicca @drkloc 

1. Log in

2. Navigate to a page where you would like to add a list of datasets

3. Click the 'Edit Panel' gear on the top right corner of the content section

4. Click the 'Add content' link on the region you would like to add the list to

5. Click on 'View Panes' from the left side options

6. Click '+Add' next to **View: DKAN Datasets Filtered: Custom Filtered Dataset List**

7. Adjust the title, pager use, tags, and/or group filters and click 'Finish'

8. Enjoy your custom filtered list of datasets

**Comment by acouch** [comment]
QA site created: http://618-filtered-dataset-pane.dkan.qa.nuamsdev.com

**Comment by drkloc** [comment]
waiting for tests to pass and merging

**Comment by acouch** [comment]
QA site created: http://618-filtered-dataset-pane.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
QA site created: http://618-filtered-dataset-pane.dkan.qa.nuamsdev.com

**Pull request merged**
