### PR TITLE
"Landing page" missing in data.json

### LINKED ISSUE #1975: landingPage missing from data.json feed
CIVIC-6512

Reported by @sheldonrampton: The landingPage field is missing from data.json feeds for datasets that have been manually created. This is happening because the schema definition for data.json fields defines the Homepage URL (landingPage) field as follows:

```
[node:field_landing_page:url]
```

Previously the landingPage field was defined as:

```
[node:url]
```

The earlier field mapping displayed the URL of the dataset where it appears on the DKAN site. The new mapping will display the URL of harvested datasets where they appear on their source websites. However, it fails for datasets that have been manually added directly to the DKAN site. To correct this, the landingPage field should be defined as:

```
[node:field_landing_page:url] || [node:url]
```

## Steps to reproduce
* Log into a DKAN site as an admin or site manager and visit the Edit API form for the Data Json 1.1 API at path /admin/config/services/odsm/edit/data_json_1_1
* Inspect the Homepage URL (landingPage) field, and you will see that it has a value of `[node:field_landing_page:url]`
* Inspect the site's data.json feed. You will see that the landingPage field is missing from datasets.
* Edit the Homepage URL (landingPage) field in the Edit API form to give it a value of `[node:field_landing_page:url] || [node:url]`
* Now re-inspect the data.json feed, and you will see that the landingPage field appears.

## Acceptance criteria

* The default value for the Homepage URL (landingPage) field in all project open data schemas should be `[node:field_landing_page:url] || [node:url]`
* The landingPage field should appear in data.json dataset listings for both harvested datasets as well as for datasets that have been manually created.

### PR DESCRIPTION
**Pull request by dafeder**
Fixes #1975

### CODE REVIEW

**Comment by dangur** [comment]
The essence of this story is complete. The only work that remains is to figure out how to get the data.json file at the webroot to read into a PHPUnit test in Circle CI. It does pass the test on my docker for mac local at http://dkan.docker/data.json

**Comment by dangur** [comment]
The essence of this story is complete. The only work that remains is to figure out how to get the data.json file at the webroot to read into a PHPUnit test in Circle CI. It does pass the test on my docker for mac local at http://dkan.docker/data.json

**Comment by dkinzer** [comment]
I flipped the order of the tests (unit test first, then behavioral tests) and unit tests started to pass but behat tests started to fail.  So that confirms that the issue might be that the tests are not cleaning up after themselves properly.

However, I added a step to reinstall dkan between the unit and behavioral steps, and now I'm still seeing one test fail in behat:

```
Then the "Homepage URL (landingPage)" field should contain "[node:field_landing_page:url] || [node:url]" # Drupal\DrupalExtension\Context\MinkContext::assertFieldContains()
      Form field with id|name|label|value "Homepage URL (landingPage)" not found. (Behat\Mink\Exception\ElementNotFoundException)
    │
    │  Current URL: http://127.0.0.1:8888/admin/config/services/odsm/edit/data_json_1_1
    │  Only a Selenium2Driver supports screenshots.
    │  Asset Captured (html dump) for step 'the "Homepage URL (landingPage)" field should contain "[node:field_landing_page:url] || [node:url]"' while at url: http://127.0.0.1:8888/admin/config/services/odsm/edit/data_json_1_1 and placed at: /home/ubuntu/dkan/dkan/test/assets/test-failure-html-dump-2017-07-26-22-35-29_the--Homepage-URL--landingPage---field-should-contain---node-field-landing-page-url------node-url--.html
    │  
    │
    └─ @AfterStep # Devinci\DevinciExtension\Context\DebugContext::dumpAssetsAfterFailedStep()

--- Failed scenarios:

    features/dataset.admin.feature:93```

That might be real?

**Comment by dkinzer** [comment]
Yup, that looks real.  When I get `/admin/config/services/odsm/edit/data_json_1_1` in probo as test specifies I get an Exception error.

I also verified it by looking at the artifacts: https://7944-9308581-gh.circle-artifacts.com/4/tmp/circle-artifacts.ETw4KOK/assets/test-failure-html-dump-2017-07-26-22-35-29_the--Homepage-URL--landingPage---field-should-contain---node-field-landing-page-url------node-url--.html

Probo doesn't run unit tests so this issue would not be related to left over unittest artifact.


## Error:

```
Additional uncaught exception thrown while handling exception.

Original

PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: SELECT ff.* FROM {filter_format} ff WHERE (status = :db_condition_placeholder_0) ORDER BY weight ASC; Array ( [:db_condition_placeholder_0] =&gt; 1 ) in filter_formats() (line 434 of /src/docroot/modules/filter/filter.module).

Additional

PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: SELECT * FROM {system} WHERE type = &#039;theme&#039; OR (type = &#039;module&#039; AND status = 1) ORDER BY weight ASC, name ASC; Array ( ) in system_list() (line 165 of /src/docroot/includes/module.inc).

Uncaught exception thrown in session handler.

PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: SELECT 1 AS expression FROM {sessions} sessions WHERE ( (sid = :db_condition_placeholder_0) AND (ssid = :db_condition_placeholder_1) ); Array ( [:db_condition_placeholder_0] =&gt; vYErBlggBa7hOhy_-yISXrMnUNBvbha1jX3T55aau4Y [:db_condition_placeholder_1] =&gt; vYErBlggBa7hOhy_-yISXrMnUNBvbha1jX3T55aau4Y ) in _drupal_session_write() (line 209 of /src/docroot/includes/session.inc).
```

**Comment by dkinzer** [comment]
I just verified that the exception is also thrown in the latest dkan_starter: https://30548b81-92bf-4b29-8591-8d88bba618b3--pr-392.probo.build/admin/config/services/odsm/edit/data_json_1_1

**Comment by dkinzer** [comment]
oh, no.  locally it's working.

**Comment by dkinzer** [comment]
OK, I verified that it's happening on devy in the acquia test environment.

**Comment by dkinzer** [comment]
Seems to be a memory thing (logs from test env on acquia):
```
php-error srv-4909 [27-Jul-2017 13:15:32 UTC] PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 11589019 bytes) in /mnt/www/html/acquiacloudprotestabm5y4gnkx/docroot/sites/all/modules/contrib/memcache/dmemcache.inc on line 64 request_id="v-ab245dc2-72cd-11e7-8040-22000a952311"
```

**Comment by dkinzer** [comment]
Locally it works, everywhere else it's running out of memory.

**Comment by dkinzer** [comment]
I now think there is something else breaking this page.  It is a memory issue on Circle but locally I can get this page to load by limiting memory to 13M.  If I limit to 12M I reproduce the memory error.

**Comment by dkinzer** [comment]
Also, I have verified that the logic to dynamically add more memory to the page is working as expected.  Which means that even when we add 512M of memory to this location it is still failing with an out of memory error.

**Pull request merged**
