### PR TITLE
Remove eva module

### PR DESCRIPTION
**Pull request by topicus**
This removes the eva module dependency for the node group page by adding plain entity queries to get the count of dataset within a group.

Require first:
https://github.com/NuCivic/dkan_dataset/pull/202
https://github.com/NuCivic/nuboot_radix/pull/55

**UPDATE**
I wasn't able to remove eva completely because it's begin used in the user view. This work will continue in https://github.com/NuCivic/dkan/issues/867

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://remove_eva_module.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://remove_eva_module.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://remove_eva_module.dkan.qa.nuamsdev.com

**Comment by acouch** [comment]
Awesome! Lets discuss if there is a proposal to remove eva from the codebase as it would require updates to existing projects.

**Comment by nucivicmachine** [comment]
QA site created: http://remove_eva_module.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://remove_eva_module.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://remove_eva_module.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://remove_eva_module.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://remove_eva_module.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://remove_eva_module.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://remove_eva_module.dkan.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://remove_eva_module.dkan.qa.nuamsdev.com

**Pull request closed without merging**
