### PR TITLE
Ahoy DKAN theme commands

### PR DESCRIPTION
**Pull request by drkloc**
#CIVIC-1909:

#### Setup for theme development

```
ahoy dkan theme setup
```

Should:
- [x] Fetch the theme to the base path where dkan lives
```
drwxr-xr-x   5 teofilosibileau  staff   170 Feb  9 17:09 backups
drwxr-xr-x  25 teofilosibileau  staff   850 Mar 23 11:34 dkan
drwxr-xr-x  30 teofilosibileau  staff  1020 Jan 28 08:41 docroot
drwxr-xr-x  32 teofilosibileau  staff  1088 Mar 22 16:42 nuboot_radix
```
- [x] Link `nuboot_radix` to `dkan/theme/contrib/nuboot_radix`
- [x] Install bower in the docker cli
- [x] Install gulp in the docker cli
- [x] Run `npm install --unsafe-perm` (needed because cli user is root)
- [x] Run `bower install -allow-root` (needed because cli user is root)

#### Compile and watch

```
ahoy dkan theme watch
````
Should:

- [x] Run gulp

### CODE REVIEW

**Comment by acouch** [comment]
:+1:

**Comment by janette** [comment]
```
(dkan)$ahoy dkan theme watch
/var/www/nuboot_radix/node_modules/node-sass/lib/extensions.js:158
    throw new Error([
          ^
Error: The `libsass` binding was not found in /var/www/nuboot_radix/node_modules/node-sass/vendor/linux-x64-14/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/var/www/nuboot_radix/node_modules/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/var/www/nuboot_radix/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/nuboot_radix/node_modules/gulp-sass/index.js:163:21)
    at Module._compile (module.js:460:26)
```

**Comment by janette** [comment]
I ran
`ahoy docker destroy`
`ahoy docker up`
`ahoy dkan theme setup`

```
ahoy dkan theme watch

> nuboot_radix@ setup /var/www/nuboot_radix
> npm install && bower install

npm WARN cannot run in wd nuboot_radix@ find node_modules/ -name '*.info' -type f -delete (wd=/var/www/nuboot_radix)
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option

npm ERR! Linux 4.1.19-boot2docker
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "setup"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE
npm ERR! nuboot_radix@ setup: `npm install && bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nuboot_radix@ setup script 'npm install && bower install'.
npm ERR! This is most likely a problem with the nuboot_radix package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls nuboot_radix
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/nuboot_radix/npm-debug.log

```

**Comment by drkloc** [comment]
please update and try again:
```
git fetch --all
git reset --hard origin/civic_1909_add_ahoy_command_to_compile_css
```

**Comment by janette** [comment]
Once I removed the nuboot_radix directory and ran the commands again I was able to get this working with out errors. Thanks @drkloc

**Pull request merged**
