### PR TITLE
Fix UI install

### LINKED ISSUE #1732: Error: Call to undefined function features_get_default() on GUI install
I am trying to install dkan-drops-7-master (the fully built version) under xampp in Windows 7 Professional. Every attempt, I get to DKAN final setup tasks and get the error:

An AJAX HTTP error occurred. HTTP Result Code: 500 Debugging information follows. Path: http://localhost/dkan/install.php?profile=dkan&locale=en&id=2&op=do StatusText: Service unavailable (with message) ResponseText: Error: Call to undefined function features_get_default() in dkan_build_menu_links() (line 270 of C:\xampp\htdocs\dkan\profiles\dkan\dkan.profile).

Is there a way to fix this and proceed?

### PR DESCRIPTION
**Pull request by acouch**
CIVIC-6070

## Description

This fixes #1732 by ensuring the ``features.export.inc`` file is available during install.

### CODE REVIEW

**Comment by dafeder** [comment]
@acouch thanks. Should the conditional be needed? `require_once()` should take care of that.

**Comment by acouch** [comment]
I couldn't get ``module_load_include()`` to work. I'm not sure why. It seems safer to use that. I'm not sure if there is a context where ``DRUPAL_ROOT`` wouldn't work. Maybe it would be better to see if that file exists and if not throw an error or note that the function didn't perform.

**Comment by dafeder** [comment]
But what i mean is, just at a PHP level require_once shouldn't let you load a file that's already loaded, right?

**Comment by acouch** [comment]
I think ``require_once()`` only loads the file once and doesn't throw an error if you have already loaded it: https://repl.it/GOqQ/6 http://stackoverflow.com/questions/2418473/difference-between-require-include-and-require-once

**Comment by acouch** [comment]
@dafeder are you waiting on anything for this? All UI installs are broken until this gets in.

**Comment by acouch** [comment]
Bump?

**Comment by dkinzer** [comment]
@acouch I tested this locally, you need to be using ` module_load_include('inc', 'features', 'features.export');`

**Comment by acouch** [comment]
@dkinzer So what does that mean? Can we pull this in already?

**Comment by acouch** [comment]
I tested this on Pantheon and the full install works without timeouts with this patch.

**Comment by dkinzer** [comment]
@acouch Your code has an error on it: 

`module_load_include('inc', 'features', 'export')` always returns false because it looks for a file called `export.inc` in the features module path which of course does not exist.

What is needed is to look for the file `features.export.inc` by using  `module_load_include('inc', 'features', 'features.export')` or `module_load_include('export.inc', 'features', 'features')`.

Please review #1818 to see if that also fixes your issue.

Thanks.

**Comment by acouch** [comment]
Argh. That looks right. Closing this issue.

**Pull request merged**
